# -*- coding=utf-8 -*-


AMAZON_OPTION = {
    "US":{
        "department_name": [
            {"value": "baby-boys", "displayname": "baby-boys"},
            {"value": "baby-girls", "displayname": "baby-girls"},
            {"value": "boys", "displayname": "boys"},
            {"value": "girls", "displayname": "girls"},
            {"value": "mens", "displayname": "mens"},
            {"value": "unisex-adult", "displayname": "unisex-adult"},
            {"value": "unisex-baby", "displayname": "unisex-baby"},
            {"value": "womens", "displayname": "womens"}
        ]
    },
    "UK": {
        "outer_material_type":  [
            {"value": "Alpaca", "displayname": "Alpaca"},
            {"value": "Angora", "displayname": "Angora"},
            {"value": "Cashmere", "displayname": "Cashmere"},
            {"value": "Corduroy", "displayname": "Corduroy"},
            {"value": "Cotton", "displayname": "Cotton"},
            {"value": "Denim", "displayname": "Denim"},
            {"value": "Down", "displayname": "Down"},
            {"value": "Faux Fur", "displayname": "Faux Fur"},
            {"value": "Felt", "displayname": "Felt"},
            {"value": "Fur", "displayname": "Fur"},
            {"value": "Hemp", "displayname": "Hemp"},
            {"value": "Leather", "displayname": "Leather"},
            {"value": "Merino", "displayname": "Merino"},
            {"value": "Mohair", "displayname": "Mohair"},
            {"value": "Patent Leather", "displayname": "Patent Leather"},
            {"value": "Rubber", "displayname": "Rubber"},
            {"value": "Satin", "displayname": "Satin"},
            {"value": "Sequined", "displayname": "Sequined"},
            {"value": "Silk", "displayname": "Silk"},
            {"value": "Smooth Leather", "displayname": "Smooth Leather"},
            {"value": "Synthetic", "displayname": "Synthetic"},
            {"value": "Velvet", "displayname": "Velvet"},
            {"value": "Wool", "displayname": "Wool"}
        ],
        "inner_material_type": [
            {"value": "Lining: Cotton", "displayname": "Lining: Cotton"},
            {"value": "Lining: Linen", "displayname": "Lining: Linen"},
            {"value": "Lining: Polyester", "displayname": "Lining: Polyester"},
            {"value": "Lining: Polyamide", "displayname": "Lining: Polyamide"},
            {"value": "Lining: Silk", "displayname": "Lining: Silk"},
            {"value": "Lining: Viscose", "displayname": "Lining: Viscose"},
            {"value": "Lining: a synthetic fiber", "displayname": "Lining: a synthetic fiber"}
        ],
        "season_and_collection_year": [
            {"value": "Autumn-Winter 12", "displayname": "Autumn-Winter 12"},
            {"value": "Autumn-Winter 13", "displayname": "Autumn-Winter 13"},
            {"value": "Autumn-Winter 14", "displayname": "Autumn-Winter 14"},
            {"value": "Autumn-Winter 15", "displayname": "Autumn-Winter 15"},
            {"value": "Autumn-Winter 16", "displayname": "Autumn-Winter 16"},
            {"value": "Autumn-Winter 17", "displayname": "Autumn-Winter 17"},
            {"value": "Autumn-Winter 18", "displayname": "Autumn-Winter 18"},
            {"value": "Spring-Summer 12", "displayname": "Spring-Summer 12"},
            {"value": "Spring-Summer 13", "displayname": "Spring-Summer 13"},
            {"value": "Spring-Summer 14", "displayname": "Spring-Summer 14"},
            {"value": "Spring-Summer 15", "displayname": "Spring-Summer 15"},
            {"value": "Spring-Summer 16", "displayname": "Spring-Summer 16"},
            {"value": "Spring-Summer 17", "displayname": "Spring-Summer 17"},
            {"value": "Spring-Summer 18", "displayname": "Spring-Summer 18"}
        ],
        "style_name": [
            {"value": "A-Line", "displayname": "A-Line"},
            {"value": "Body Con", "displayname": "Body Con"},
            {"value": "Bubble Hem", "displayname": "Bubble Hem"},
            {"value": "Bustier", "displayname": "Bustier"},
            {"value": "Cocktail", "displayname": "Cocktail"},
            {"value": "Column", "displayname": "Column"},
            {"value": "Cut-Out", "displayname": "Cut-Out"},
            {"value": "Empire", "displayname": "Empire"},
            {"value": "Halterneck", "displayname": "Halterneck"},
            {"value": "Jumper", "displayname": "Jumper"},
            {"value": "Kimono", "displayname": "Kimono"},
            {"value": "Pencil", "displayname": "Pencil"},
            {"value": "Peplum", "displayname": "Peplum"},
            {"value": "Pleated", "displayname": "Pleated"},
            {"value": "Shirt", "displayname": "Shirt"},
            {"value": "Skater", "displayname": "Skater"},
            {"value": "Strapless", "displayname": "Strapless"},
            {"value": "Tulip", "displayname": "Tulip"},
            {"value": "Tunic", "displayname": "Tunic"},
            {"value": "Wrap", "displayname": "Wrap"}
        ],
            "department_name": [
            {"value": "Baby-Boys", "displayname": "Baby-Boys"},
            {"value": "Baby-Girls", "displayname": "Baby-Girls"},
            {"value": "Boys", "displayname": "Boys"},
            {"value": "Girls", "displayname": "Girls"},
            {"value": "Men", "displayname": "Men"},
            {"value": "Women", "displayname": "Women"}
            ]
    },
    "FR": {
        "outer_material_type": [
            {"value": "Alpaca", "displayname": "Alpaca"},
            {"value": "Angora", "displayname": "Angora"},
            {"value": "Cachemire", "displayname": "Cachemire"},
            {"value": "Caoutchouc", "displayname": "Caoutchouc"},
            {"value": "Chanvre", "displayname": "Chanvre"},
            {"value": "Cotton", "displayname": "Cotton"},
            {"value": "Cuir", "displayname": "Cuir"},
            {"value": "Cuir lisse", "displayname": "Cuir lisse"},
            {"value": "Cuir vernis", "displayname": "Cuir vernis"},
            {"value": "Denim", "displayname": "Denim"},
            {"value": "Duvet", "displayname": "Duvet"},
            {"value": "Fausse fourrure", "displayname": "Fausse fourrure"},
            {"value": "Feutre", "displayname": "Feutre"},
            {"value": "Fourrure", "displayname": "Fourrure"},
            {"value": "Laine", "displayname": "Laine"},
            {"value": "Lin", "displayname": "Lin"},
            {"value": "Merino", "displayname": "Merino"},
            {"value": "Mohair", "displayname": "Mohair"},
            {"value": "Pailleté", "displayname": "Pailleté"},
            {"value": "Polaire", "displayname": "Polaire"},
            {"value": "Satin", "displayname": "Satin"},
            {"value": "Soie", "displayname": "Soie"},
            {"value": "Suède", "displayname": "Suède"},
            {"value": "Synthétique", "displayname": "Synthétique"},
            {"value": "Velours", "displayname": "Velours"},
            {"value": "Velours côtelé", "displayname": "Velours côtelé"}
        ],
        "inner_material_type":  [
            {"value": "Doublure: Coton", "displayname": "Doublure: Coton"},
            {"value": "Doublure: Fibres syntétiques", "displayname": "Doublure: Fibres syntétiques"},
            {"value": "Doublure: Lin", "displayname": "Doublure: Lin"},
            {"value": "Doublure: Polyamide", "displayname": "Doublure: Polyamide"},
            {"value": "Doublure: Polyester", "displayname": "Doublure: Polyester"},
            {"value": "Doublure: Soie", "displayname": "Doublure: Soie"},
            {"value": "Doublure: Viscose", "displayname": "Doublure: Viscose"}
        ],
        "season_and_collection_year": [
            {"value": "Automne-hiver 12", "displayname": "Automne-hiver 12"},
            {"value": "Automne-hiver 13", "displayname": "Automne-hiver 13"},
            {"value": "Automne-hiver 14", "displayname": "Automne-hiver 14"},
            {"value": "Automne-hiver 15", "displayname": "Automne-hiver 15"},
            {"value": "Automne-hiver 16", "displayname": "Automne-hiver 16"},
            {"value": "Automne-hiver 17", "displayname": "Automne-hiver 17"},
            {"value": "Automne-hiver 18", "displayname": "Automne-hiver 18"},
            {"value": "Printemps-été 12", "displayname": "Printemps-été 12"},
            {"value": "Printemps-été 13", "displayname": "Printemps-été 13"},
            {"value": "Printemps-été 14", "displayname": "Printemps-été 14"},
            {"value": "Printemps-été 15", "displayname": "Printemps-été 15"},
            {"value": "Printemps-été 16", "displayname": "Printemps-été 16"},
            {"value": "Printemps-été 17", "displayname": "Printemps-été 17"},
            {"value": "Printemps-été 18", "displayname": "Printemps-été 18"}
        ],
        "style_name":  [
            {"value": "Blouson", "displayname": "Blouson"},
            {"value": "Caban", "displayname": "Caban"},
            {"value": "Cape", "displayname": "Cape"},
            {"value": "Doudoune", "displayname": "Doudoune"},
            {"value": "Duffle coat", "displayname": "Duffle coat"},
            {"value": "Parka", "displayname": "Parka"},
            {"value": "Teddy", "displayname": "Teddy"},
            {"value": "Trench", "displayname": "Trench"},
            {"value": "Veste damassée", "displayname": "Veste damassée"}
        ],
        "department_name":  [
            {"value": "Bébé fille", "displayname": "Bébé fille"},
            {"value": "Bébé garçon", "displayname": "Bébé garçon"},
            {"value": "Femme", "displayname": "Femme"},
            {"value": "Fille", "displayname": "Fille"},
            {"value": "Garçon", "displayname": "Garçon"},
            {"value": "Homme", "displayname": "Homme"}
            ]
    },
    "DE": {
        "outer_material_type": [
            {"value": "Alpaka", "displayname": "Alpaka"},
            {"value": "Angora", "displayname": "Angora"},
            {"value": "Baumwolle", "displayname": "Baumwolle"},
            {"value": "Cord", "displayname": "Cord"},
            {"value": "Daunen", "displayname": "Daunen"},
            {"value": "Filz", "displayname": "Filz"},
            {"value": "Fleece", "displayname": "Fleece"},
            {"value": "Glattleder", "displayname": "Glattleder"},
            {"value": "Gummi", "displayname": "Gummi"},
            {"value": "Hanf", "displayname": "Hanf"},
            {"value": "Jeans", "displayname": "Jeans"},
            {"value": "Kaschmir", "displayname": "Kaschmir"},
            {"value": "Lackleder", "displayname": "Lackleder"},
            {"value": "Leder", "displayname": "Leder"},
            {"value": "Leinen", "displayname": "Leinen"},
            {"value": "Merino", "displayname": "Mohair"},
            {"value": "Pailletten", "displayname": "Pailletten"},
            {"value": "Pelz", "displayname": "Pelz"},
            {"value": "Pelzimitat", "displayname": "Pelzimitat"},
            {"value": "Samt", "displayname": "Samt"},
            {"value": "Satin", "displayname": "Satin"},
            {"value": "Seide", "displayname": "Seide"},
            {"value": "Synthetisch", "displayname": "Synthetisch"},
            {"value": "Wildleder", "displayname": "Wildleder"},
            {"value": "Wolle", "displayname": "Wolle"}
        ],
        "inner_material_type": [
            {"value": "Lining: Baumwolle", "displayname": "Lining: Baumwolle"},
            {"value": "Lining: Leinen", "displayname": "Lining: Leinen"},
            {"value": "Lining: Polyamide", "displayname": "Lining: Polyamide"},
            {"value": "Lining: Polyester", "displayname": "Lining: Polyester"},
            {"value": "Lining: Seide", "displayname": "Lining: Seide"},
            {"value": "Lining: Synthetik", "displayname": "Lining: Synthetik"},
            {"value": "Lining: Viskose", "displayname": "Lining: Viskose"}
        ],
        "season_and_collection_year":  [
            {"value": "Frühjahr-Sommer 12", "displayname": "Frühjahr-Sommer 12"},
            {"value": "Frühjahr-Sommer 13", "displayname": "Frühjahr-Sommer 13"},
            {"value": "Frühjahr-Sommer 14", "displayname": "Frühjahr-Sommer 14"},
            {"value": "Frühjahr-Sommer 15", "displayname": "Frühjahr-Sommer 15"},
            {"value": "Frühjahr-Sommer 16", "displayname": "Frühjahr-Sommer 16"},
            {"value": "Frühjahr-Sommer 17", "displayname": "Frühjahr-Sommer 17"},
            {"value": "Frühjahr-Sommer 18", "displayname": "Frühjahr-Sommer 18"},
            {"value": "Herbst-Winter 12", "displayname": "Herbst-Winter 12"},
            {"value": "Herbst-Winter 13", "displayname": "Herbst-Winter 13"},
            {"value": "Herbst-Winter 14", "displayname": "Herbst-Winter 14"},
            {"value": "Herbst-Winter 15", "displayname": "Herbst-Winter 15"},
            {"value": "Herbst-Winter 16", "displayname": "Herbst-Winter 16"},
            {"value": "Herbst-Winter 17", "displayname": "Herbst-Winter 17"},
            {"value": "Herbst-Winter 18", "displayname": "Herbst-Winter 18"}
        ],
        "style_name": [
            {"value": "Blouson", "displayname": "Blouson"},
            {"value": "Collegejacke", "displayname": "Collegejacke"},
            {"value": "Daunen", "displayname": "Daunen"},
            {"value": "Duffle", "displayname": "Duffle"},
            {"value": "Parka", "displayname": "Parka"},
            {"value": "Seemannsjacke", "displayname": "Seemannsjacke"},
            {"value": "Steppjacke", "displayname": "Steppjacke"},
            {"value": "Trench", "displayname": "Trench"},
            {"value": "Umhang", "displayname": "Umhang"}
        ],
        "department_name": [
            {"value": "Baby - Jungen", "displayname": "Baby - Jungen"},
            {"value": "Baby - Mädchen", "displayname": "Baby - Mädchen"},
            {"value": "Damen", "displayname": "Damen"},
            {"value": "Herren", "displayname": "Herren"},
            {"value": "Jungen", "displayname": "Jungen"},
            {"value": "Mädchen", "displayname": "Mädchen"}
            ]
    }
}