# -*- coding: utf-8 -*-


color_dict = {
    u'深石板蓝': "dark slate blue",
    u'光明绿松石': "bright turquoise",
    u'罂粟红': "coquelicot",
    u'砒霜': "arsenic",
    u'深灰': "slate gray",
    u'仿古黑': "antique black",
    u'波特兰橙': "portland orange",
    u'霓虹紫红': "neon fuchsia",
    u'芭比粉红': "barbie pink",
    u'橄榄绿': "olive green",
    u'霜白': "frost white",
    u'酞菁绿': "phthalo green",
    u'达特茅斯绿': "dartmouth green",
    u'镉红': "cadmium red",
    u'纯': "pure",
    u'青瓷绿': "celadon green",
    u'探戈粉': "tango pink",
    u'银湖蓝': "silver lake blue",
    u'暗赭': "dark sienna",
    u'暗金': "dark blond",
    u'纽约粉红': "new york pink",
    u'卡尔波利绿': "cal poly green",
    u'深紫': "navy purple",
    u'电青': "electric cyan",
    u'水鸭蓝': "teal blue",
    u'镉黄': "cadmium yellow",
    u'镉绿': "cadmium green",
    u'英国紫罗兰': "english violet",
    u'法国褐': "french bistre",
    u'赭': "sienna",
    u'树莓粉红': "raspberry pink",
    u'浅石板灰': "light slate gray",
    u'豹纹': "leopard print",
    u'西班牙天蓝': "spanish sky blue",
    u'香蕉黄': "banana yellow",
    u'深褐棕': "bistre brown",
    u'水獭棕': "otter brown",
    u'知更鸟蛋青': "robin egg blue",
    u'尖叫绿': "screamin' green",
    u'绯红': "ku crimson",
    u'深丛林绿': "deep jungle green",
    u'大倾角红宝石': "big dip o'ruby",
    u'三叶草绿': "shamrock green",
    u'玫瑰糖果': "rose bonbon",
    u'深灰褐': "deep taupe",
    u'浅粉': "light pink",
    u'暗紫': "dark purple",
    u'宝石蓝': "moonstone blue",
    u'巴基斯坦绿': "pakistan green",
    u'薄荷': "mint",
    u'间绿宝石': "medium turquoise",
    u'康乃馨粉': "carnation pink",
    u'火烈鸟粉': "flamingo pink",
    u'牛仔蓝': "denim blue",
    u'加亮': "highlight",
    u'金丝雀黄': "canary yellow",
    u'浅黄褐': "fawn",
    u'金属红': "metallic red",
    u'大理石': "marble",
    u'日本靛蓝': "japanese indigo",
    u'绿珍珠': "green pearl",
    u'花斑': "harlequin",
    u'黄': "yellow",
    u'漆黑': "midnight",
    u'分辨率蓝': "resolution blue",
    u'白': "white",
    u'透明珍珠绿': "clear green pearl",
    u'虎眼石': "tiger's eye",
    u'宫廷黄': "royal yellow",
    u'孔雀蓝': "peacock blue",
    u'粉红': "rose",
    u'湖绿': "lake green",
    u'中国紫': "chinese violet",
    u'苹果绿': "apple green",
    u'淡绿': "acid green",
    u'孔雀鱼绿': "guppie green",
    u'淡黄': "mellow yellow",
    u'绿格子': "green plaid",
    u'水鸭绿': "teal green",
    u'卡塔利娜蓝': "catalina blue",
    u'法国玫瑰': "french rose",
    u'象牙': "ivory",
    u'暗红': "burgundy",
    u'古金': "antique gold",
    u'淡品红': "pale magenta",
    u'黑咖啡': "dark coffee",
    u'巧克力': "chocolate",
    u'五彩': "multicolored",
    u'矢车菊': "bluebonnet",
    u'奶白': "milk white",
    u'栗': "maroon",
    u'沙': "sand",
    u'琥珀': "amber",
    u'玉米': "maize",
    u'中国红': "chinese red",
    u'绿宝石': "emerald",
    u'浓郁丁香花': "rich lilac",
    u'海贝': "seashell",
    u'迷彩绿': "camouflage green",
    u'淡蓝珍珠': "light blue pearl",
    u'雷勒蓝': "majorelle blue",
    u'绿松石蓝': "turquoise blue",
    u'束兰': "tufts blue",
    u'伊顿蓝': "eton blue",
    u'黄金融合': "gold fusion",
    u'淡金黄': "pale goldenrod",
    u'朱砂': "cinnabar",
    u'皇家紫红': "royal fuchsia",
    u'浅绛红': "purple light",
    u'苔黑绿': "dark moss green",
    u'琥珀金': "amber gold",
    u'西班牙橙': "spanish orange",
    u'西班牙深红': "spanish crimson",
    u'鲜粉红': "shocking pink",
    u'藤黄': "gamboge",
    u'水蓝': "water blue",
    u'浓郁胭脂红': "rich carmine",
    u'孔雀石绿': "malachite",
    u'芒果探戈': "mango tango",
    u'印度绿': "india green",
    u'金莲花': "bole",
    u'烟熏黑': "smoky black",
    u'印度黄': "indian yellow",
    u'深兰花紫': "dark orchid",
    u'土耳其玫瑰': "turkish rose",
    u'法国淡紫': "french mauve",
    u'金属紫': "metallic purple",
    u'暗红橙': "burnt sienna",
    u'水洗黑': "washed black",
    u'深柠檬': "deep lemon",
    u'浅卡其': "light khaki",
    u'印度红': "indian red",
    u'北极蓝': "arctic blue",
    u'淡棕': "pale brown",
    u'香橼': "citron",
    u'深肝': "dark liver",
    u'碳纤维黑': "carbon fiber black",
    u'糖果粉': "candy pink",
    u'金属银': "metallic silver",
    u'浅粉红': "baby pink",
    u'可可棕': "cocoa brown",
    u'梦境': "dreamscape",
    u'蒂芙尼蓝': "tiffany blue",
    u'光海绿': "light sea green",
    u'金罂粟': "golden poppy",
    u'冷白': "cool white",
    u'薰衣草粉红': "lavender pink",
    u'透明珍珠粉': "clear pink pearl",
    u'蓝宝石': "blue sapphire",
    u'深香蕉': "banana mania",
    u'皇家蓝': "royal blue",
    u'夕阳橙': "sunset orange",
    u'蜂蜜': "honey",
    u'局部黄': "selective yellow",
    u'青古铜': "antique bronze",
    u'木褐': "wood brown",
    u'金鱼': "goldfish",
    u'蛋壳': "eggshell",
    u'中海蓝': "medium sea green",
    u'航空蓝': "aero blue",
    u'查尔斯顿绿': "charleston green",
    u'俄罗斯紫罗兰': "russian violet",
    u'金褐': "golden brown",
    u'茄子': "eggplant",
    u'透明': "transparent",
    u'粉红靛蓝': "pink indigo",
    u'中紫': "medium purple",
    u'电蓝': "electric blue",
    u'肯尼亚铜': "kenyan copper",
    u'粉蓝': "baby blue",
    u'深栗': "deep chestnut",
    u'牛仔': "denim",
    u'肉棕': "meat brown",
    u'巧克力蓝': "blue chocolate",
    u'黑天蓝': "dark cerulean",
    u'中金发': "medium blond",
    u'暗黄': "dark yellow",
    u'生褐': "raw umber",
    u'爱丽丝蓝': "alice blue",
    u'黄迷彩': "yellow camouflage",
    u'玛雅蓝': "maya blue",
    u'旧布黄': "old lace",
    u'法国石灰': "french lime",
    u'午夜绿': "midnight green",
    u'中丛林绿': "medium jungle green",
    u'绚丽薰衣草': "rich brilliant lavender",
    u'深蓝灰': "slate",
    u'暴雪蓝': "blizzard blue",
    u'石英': "quartz",
    u'深桃': "deep peach",
    u'柔和灰': "pastel gray",
    u'斑马纹': "zebra print",
    u'桔黄': "tangerine yellow",
    u'姜': "ginger",
    u'葡萄酒红': "wine red",
    u'波斯蓝': "persian blue",
    u'松绿': "pine green",
    u'亮红': "bright red",
    u'深军绿': "dark army green",
    u'深卡其': "dark khaki",
    u'狮子': "lion",
    u'暗灰褐': "dark taupe",
    u'中春绿': "medium spring green",
    u'浅杏': "light apricot",
    u'淡草绿': "pistachio",
    u'时尚紫红': "fashion fuchsia",
    u'翡翠': "jade",
    u'珍珠紫': "pearly purple",
    u'美国玫瑰': "american rose",
    u'浓黄': "goldenrod",
    u'经典玫瑰': "classic rose",
    u'朱砂粉红': "carmine pink",
    u'埃及蓝': "egyptian blue",
    u'玫瑰粉': "rose pink",
    u'绿黄': "lime",
    u'鲜黄绿': "kelly green",
    u'法国丁香花': "french lilac",
    u'卡斯尔顿绿': "castleton green",
    u'透明粉': "clear pink",
    u'云母': "mica",
    u'黑珊瑚': "dark coral",
    u'西班牙褐': "spanish bistre",
    u'黑皮夹克': "black leather jacket",
    u'淺紫': "lilac",
    u'蔚蓝': "sapphire",
    u'橙格子': "orange plaid",
    u'红基': "radical red",
    u'宝蓝亮': "bright navy blue",
    u'深石板灰': "dark slate gray",
    u'赭石': "sinopia",
    u'汉紫': "han purple",
    u'马革': "cordovan",
    u'拖拉机红': "tractor red",
    u'镉橙': "cadmium orange",
    u'复古淡紫': "old mauve",
    u'灰黑': "ash black",
    u'金矿': "goldmine",
    u'柠檬绿': "lime green",
    u'黑电蓝': "dark electric blue",
    u'柠檬黄': "lemon yellow",
    u'伊斯兰绿': "islamic green",
    u'透明黄': "clear beige",
    u'深藏红花': "deep saffron",
    u'喇沙绿': "la salle green",
    u'透明白': "transparent white",
    u'木莓红': "raspberry rose",
    u'深棕': "dark brown",
    u'深空蓝': "deep sky blue",
    u'大丽花': "dahlia",
    u'粉': "pink",
    u'深粉红': "dark pink",
    u'铜红': "copper red",
    u'绿松石黑': "turquoise black",
    u'山地草甸': "mountain meadow",
    u'褐': "bistre",
    u'樱桃': "cherry",
    u'深香槟': "deep champagne",
    u'水仙': "daffodil",
    u'宝蓝': "sapphire blue",
    u' 森林绿': "hunter green",
    u'沙灰褐': "sandy taupe",
    u'粉红豹纹': "pink cheetah",
    u'杏': "almond",
    u'魅惑粉红': "charm pink",
    u'柔和绿': "pastel green",
    u'铜绿': "verdigris",
    u'渐变黑': "gradient black",
    u'深绿': "dark green",
    u'浅绿': "light green",
    u'暗柔和紫': "dark pastel purple",
    u'电石灰': "electric lime",
    u'光洗蓝': "blue light wash",
    u'热情洋红': "hot magenta",
    u'浅绛彩': "light crimson",
    u'黑暗帝国蓝': "dark imperial blue",
    u'深红宝石': "deep ruby",
    u'银绿': "silver green",
    u'浅青': "light cyan",
    u'松石绿': "turquoise green",
    u'英国薰衣草': "english lavender",
    u'湖蓝': "lake blue",
    u'焦橙': "burnt orange",
    u'青铜黄': "bronze yellow",
    u'橙': "orange",
    u'亮薰衣草': "bright lavender",
    u'未漂白丝': "unbleached silk",
    u'晶莹剔透': "crystal clear",
    u'非洲紫': "african purple",
    u'绿苹果': "green apple",
    u'西班牙灰': "spanish gray",
    u'霓虹粉红': "neon pink",
    u'霓虹蓝': "neon blue",
    u'牛奶巧克力': "milk chocolate",
    u'桔红': "nacarat",
    u'钴蓝': "cobalt",
    u'萤光粉红': "fluorescent pink",
    u'航空': "aero",
    u'海军蓝': "navy",
    u'天青': "celeste",
    u'法国蓝': "french blue",
    u'透明绿': "clear green",
    u'浅钢蓝': "light steel blue",
    u'中度碧绿': "medium aquamarine",
    u'花卉白': "floral white",
    u'柔和紫': "pastel violet",
    u'灿烂玫瑰': "brilliant rose",
    u'CG蓝': "cg blue",
    u'卡蓝': "carolina blue",
    u'边缘粉红': "brink pink",
    u'檀香山蓝': "honolulu blue",
    u'光泽绿': "sheen green",
    u'深鲜肉': "dark salmon",
    u'黑橘': "dark tangerine",
    u'亮天蓝': "bright cerulean",
    u'郁金香': "tulip",
    u'金属粉红': "metallic pink",
    u'淡知更鸟蛋青': "pale robin egg blue",
    u'淡褐': "ecru",
    u'玫瑰红': "rose red",
    u'夹竹桃': "phlox",
    u'亮粉红': "bright pink",
    u'中天蓝': "medium sky blue",
    u'好莱坞樱桃': "hollywood cerise",
    u'暖黄': "warm yellow",
    u'拿浦黄': "naples yellow",
    u'珠光': "bittersweet shimmer",
    u'彩': "multicolor",
    u'玉米穗黄': "cornsilk",
    u'哑光白': "matte white",
    u'暖黑': "warm black",
    u'中国粉红': "china pink",
    u'浅橙红': "light salmon pink",
    u'裸': "nude",
    u'彩虹': "iridescent",
    u'浅紫': "light purple",
    u'银灰': "silver gray",
    u'斑纹': "zebra",
    u'灰褐': "taupe",
    u'藏青': "navy blue",
    u'春绿': "spring green",
    u'睛蓝': "baby blue eyes",
    u'铁蓝': "prussian blue",
    u'猩红': "scarlet",
    u'香柏木箱': "cedar chest",
    u'青灰': "livid",
    u'格子': "ceil",
    u'哈佛深红': "harvard crimson",
    u'格子白': "checkered white",
    u'黑兵马俑': "dark terra cotta",
    u'西瓜红': "watermelon red",
    u'浅棕': "light brown",
    u'光苔绿': "light moss green",
    u'卡其绿': "khaki green",
    u'英国赛车绿': "british racing green",
    u'熟杏': "mellow apricot",
    u'金属玛瑙': "metallic onyx",
    u'海洋之舟蓝': "ocean boat blue",
    u'小猪粉红': "piggy pink",
    u'淡粉紫': "light orchid",
    u'熔岩': "lava",
    u'中春芽': "medium spring bud",
    u'蒙巴顿粉红': "mountbatten pink",
    u'金属海藻': "metallic seaweed",
    u'玫瑰灰褐': "rose taupe",
    u'灰': "grey",
    u'咖啡': "coffee",
    u'红珍珠': "red pearl",
    u'斯巴达深红': "spartan crimson",
    u'鲜绿': "viridian green",
    u'黄玫瑰': "yellow rose",
    u'鸢尾花': "iris",
    u'青莲': "heliotrope",
    u'意大利天空蓝': "italian sky blue",
    u'蓝灰': "cadet grey",
    u'沥青': "asphalt",
    u'矢车菊蓝': "cornflower blue",
    u'芥末黄': "harvest gold",
    u'布伦瑞克绿': "brunswick green",
    u'中薰衣草品红': "medium lavender magenta",
    u'泡泡糖粉': "bubblegum pink",
    u'红葡萄酒': "claret",
    u'自然': "natural",
    u'女王粉': "queen pink",
    u'石榴': "garnet",
    u'亚麻': "flax",
    u'淡栗': "pale chestnut",
    u'耶鲁蓝': "yale blue",
    u'糖果苹果红': "candy apple red",
    u'沙漠沙': "desert sand",
    u'林肯绿': "lincoln green",
    u'波斯靛': "persian indigo",
    u'托斯卡纳红': "tuscan red",
    u'紫红': "wine",
    u'皇室香槟': "imperial",
    u'中等托斯卡纳红': "medium tuscan red",
    u'西班牙胭脂红': "spanish carmine",
    u'日本紫罗兰': "japanese violet",
    u'纳瓦霍白': "navajo white",
    u'原木': "burlywood",
    u'荷兰白': "dutch white",
    u'赤褐': "russet",
    u'带黄粉红': "tea rose",
    u'兰花紫': "orchid",
    u'虎纹': "tiger print",
    u'中胭脂红': "medium carmine",
    u'天空蓝': "sky blue",
    u'稍带黄': "flavescent",
    u'法国深褐': "french puce",
    u'中灰褐': "medium taupe",
    u'白雾': "white smoke",
    u'芥末': "mustard",
    u'青苹果': "granny smith apple",
    u'闪光白': "sparkling white",
    u'粉红紫绿': "pink purple green",
    u'法拉利红': "ferrari red",
    u'暗洋红': "dark magenta",
    u'黄橙': "yellow orange",
    u'暗栗': "dark chestnut",
    u'深托斯卡纳红': "deep tuscan red",
    u'橘黄': "saffron",
    u'薰衣草蓝': "lavender indigo",
    u'胡萝卜橙': "carrot orange",
    u'中等糖果苹果红': "medium candy apple red",
    u'公爵蓝': "duke blue",
    u'军校蓝': "cadet blue",
    u'淡粉': "pale pink",
    u'薰衣草': "lavender",
    u'柠檬': "lemon",
    u'暮光之城薰衣草': "twilight lavender",
    u'蕨绿': "fern green",
    u'石板蓝': "slate blue",
    u'胭脂红': "carmine red",
    u'蜜桔': "atomic tangerine",
    u'薰衣草品红': "lavender magenta",
    u'俄罗斯绿': "russian green",
    u'联合国蓝': "united nations blue",
    u'珊瑚': "coral",
    u'堇紫': "pansy purple",
    u'靛蓝': "indigo",
    u'电紫罗兰': "electric violet",
    u'中电蓝': "medium electric blue",
    u'透明灰': "clear gray",
    u'法国米黄': "french beige",
    u'红木': "redwood",
    u'加勒比海绿': "caribbean green",
    u'仿古白': "antique white",
    u'戴维灰': "davy's grey",
    u'红润': "ruddy",
    u'午夜黑蓝': "dark midnight blue",
    u'电群青': "electric ultramarine",
    u'石楠灰': "heather grey",
    u'海绿': "sea green",
    u'铬黄': "chrome yellow",
    u'森林迷彩': "forest camouflage",
    u'青铜': "bronze",
    u'霓虹红': "neon red",
    u'银': "silver",
    u'爱尔兰绿': "irish green",
    u'熟褐': "burnt umber",
    u'茜素玫瑰红': "rose madder",
    u'白杏': "blanched almond",
    u'淡粉蓝': "pale turquoise",
    u'紫灰': "dark byzantium",
    u'古董红宝石': "antique ruby",
    u'墨黑': "jet",
    u'钞票': "dollar bill",
    u'铬绿': "viridian",
    u'薄荷迷彩': "magic mint",
    u'橄榄绿黑': "olive green black",
    u'英国绿': "english green",
    u'薄荷绿': "mint green",
    u'桃紅': "fuchsia",
    u'墨红': "crimson glory",
    u'阿拉巴马绯红': "alabama crimson",
    u'女王蓝': "queen blue",
    u'草莓': "strawberry",
    u'酷黑': "cool black",
    u'深丁香花': "deep lilac",
    u'明亮': "bright ube",
    u'莫卧儿绿': "mughal green",
    u'钢蓝': "steel blue",
    u'青瓷': "celadon",
    u'深石灰': "bitter lime",
    u'深粉蓝': "dark powder blue",
    u'午夜蓝': "midnight blue",
    u'巧克力棕': "chocolate brown",
    u'电黄': "electric yellow",
    u'粉黄': "pastel yellow",
    u'电绿': "electric green",
    u'黄绿': "olivine",
    u'深橙': "dark orange",
    u'桃红': "peach",
    u'黑紫红': "black fuchsia",
    u'海带绿': "kombu green",
    u'深赤褐': "liver",
    u'黯淡白': "off white",
    u'耐火砖': "firebrick",
    u'深胭脂红粉': "deep carmine pink",
    u'酒红': "berry",
    u'长春花': "periwinkle",
    u'淡胭脂红': "pale carmine",
    u'深': "deep",
    u'铜': "copper penny",
    u'康奈尔红': "cornell red",
    u'荧光橙': "fluorescent orange",
    u'仿古紫红': "antique fuchsia",
    u'瓯深红': "ou crimson red",
    u'黑灰': "black gray",
    u'海牛': "manatee",
    u'电红': "electric crimson",
    u'甘草': "licorice",
    u'驼': "light tan",
    u'复古薰衣草': "old lavender",
    u'薰衣草雾': "lavender mist",
    u'芦笋绿': "asparagus",
    u'酞菁蓝': "phthalo blue",
    u'邦迪蓝': "bondi blue",
    u'黄水晶': "citrine",
    u'山茱萸玫瑰': "dogwood rose",
    u'中石板蓝': "medium slate blue",
    u'霓虹黄': "neon yellow",
    u'雪白': "snow",
    u'白桦': "birch",
    u'洋蓝': "yankees blue",
    u'消防车红': "fire engine red",
    u'玛瑙': "onyx",
    u'暗朱红': "dark scarlet",
    u'深胭脂红': "deep carmine",
    u'小麦': "wheat",
    u'浅灰蓝': "powder blue",
    u'大红': "cardinal",
    u'电紫': "electric purple",
    u'深橄榄绿': "dark olive green",
    u'天蓝橙': "skyblue orange",
    u'波斯橙': "persian orange",
    u'英国红': "english red",
    u'红': "red",
    u'浅肉': "light salmon",
    u'驴棕': "donkey brown",
    u'淡灰褐': "pale taupe",
    u'兰花粉红': "orchid pink",
    u'米卡多黄': "mikado yellow",
    u'中蓝': "medium blue",
    u'苹果红': "dark candy apple red",
    u'玫瑰': "rose gold",
    u'深蓝': "ultramarine blue",
    u'淡紫': "pale lavender",
    u'碧绿': "aquamarine",
    u'皇家紫': "imperial purple",
    u'校车黄': "school bus yellow",
    u'浓郁栗': "rich maroon",
    u'抚子粉': "nadeshiko pink",
    u'浅黄': "light yellow",
    u'天空红': "sky magenta",
    u'光胭脂红粉红': "light carmine pink",
    u'烟熏黄': "smokey topaz",
    u'纯白': "pure white",
    u'海狸': "beaver",
    u'紫铜': "copper",
    u'宝石黄': "topaz",
    u'黑豆': "black bean",
    u'银粉': "silver pink",
    u'深青': "teal",
    u'莺橙': "orioles orange",
    u'亮灰': "gainsboro",
    u'深蓝珍珠': "dark blue pearl",
    u'靛青': "indigo dye",
    u'电薰衣草': "electric lavender",
    u'暗柔和绿': "dark pastel green",
    u'格子红': "checkered red",
    u'米': "beige",
    u'粉红薰衣草': "pink lavender",
    u'紫檀木': "rosewood",
    u'森林绿': "up forest green",
    u'亮珊瑚': "light coral",
    u'薰衣草紫': "lavender blush",
    u'布兰代斯蓝': "brandeis blue",
    u'切达黄': "cheddar yellow",
    u'蓝雾': "azure mist",
    u'迷彩': "camouflage",
    u'复古苔绿': "old moss green",
    u'激光柠檬': "laser lemon",
    u'霓虹橙': "neon orange",
    u'米黄': "mode beige",
    u'红糖': "brown sugar",
    u'亮栗': "bright maroon",
    u'透明粉红': "transparent pink",
    u'焦茶': "umber",
    u'墨粉': "mexican pink",
    u'黑树莓': "dark raspberry",
    u'洗蓝': "blue wash",
    u'谷仓红': "barn red",
    u'杏黄': "apricot",
    u'卡其': "khaki",
    u'丛林黑绿': "dark jungle green",
    u'淡银': "pale silver",
    u'深蓝紫': "purple navy",
    u'凡丹戈粉': "fandango pink",
    u'北德州绿': "north texas green",
    u'深天空蓝': "dark sky blue",
    u'紫': "purple",
    u'中褐': "medium brown",
    u'樱桃粉': "cherry pink",
    u'金黄': "gold",
    u'暗绿松石': "dark turquoise",
    u'柔和棕': "pastel brown",
    u'棕': "brown",
    u'浅蓝': "light blue",
    u'步枪绿': "rifle green",
    u'青柠檬': "lemon lime",
    u'托斯卡纳棕': "tuscan brown",
    u'托斯卡纳棕褐': "tuscan tan",
    u'钴黄': "aureolin",
    u'钢粉': "steel pink",
    u'浅灰': "light grey",
    u'蓝紫': "royal purple",
    u'冷灰': "cool grey",
    u'黑白': "black white",
    u'黑熔岩': "dark lava",
    u'中红宝石': "medium ruby",
    u'紫藤': "wisteria",
    u'珊瑚红': "coral red",
    u'椰子': "coconut",
    u'黄褐': "drab",
    u'黑香草': "dark vanilla",
    u'透明蓝': "clear blue",
    u'深褐': "seal brown",
    u'中国玫瑰': "china rose",
    u'棕褐': "tan",
    u'橙红': "salmon pink",
    u'白金': "white gold",
    u'古铜': "antique brass",
    u'波斯粉': "persian pink",
    u'黑橄榄': "black olive",
    u'黑褐': "black brown",
    u'柠檬白': "lemon meringue",
    u'浅金黄': "light goldenrod yellow",
    u'深春绿': "dark spring green",
    u'浓郁铁蓝': "rich electric blue",
    u'锈褐': "rust brown",
    u'丛林绿': "jungle green",
    u'珊瑚绿': "coral green",
    u'深洋红': "deep magenta",
    u'柔和粉红': "pastel pink",
    u'薰衣草灰': "lavender gray",
    u'浅米': "light beige",
    u'红褐': "vivid auburn",
    u'红黑': "red black",
    u'水绿': "aqua",
    u'长颈鹿': "giraffe",
    u'橄榄': "olive drab",
    u'青绿': "turquoise",
    u'樱花粉': "cherry blossom pink",
    u'青瓷蓝': "celadon blue",
    u'黑薰衣草': "dark lavender",
    u'亮蓝': "bright blue",
    u'灰白': "grey white",
    u'炭': "charcoal",
    u'淡蓝': "pastel blue",
    u'深苔绿': "deep moss green",
    u'鬼白': "ghost white",
    u'暗海绿': "dark sea green",
    u'钛黄': "titanium yellow",
    u'深樱桃': "deep cerise",
    u'五月绿': "may green",
    u'印花': "floral print",
    u'暗褐': "sepia",
    u'嫩绿': "peak green",
    u'柔和品红': "pastel magenta",
    u'晶蓝': "ball blue",
    u'暗黄绿': "avocado",
    u'普林斯顿橙': "princeton orange",
    u'浅玫瑰': "light rose",
    u'火红': "red hot",
    u'蓝': "blue",
    u'赤土': "terra cotta",
    u'浅灰褐': "light taupe",
    u'超级粉': "super pink",
    u'苔绿': "moss green",
    u'蓝莓': "blueberry",
    u'汉沙黄': "hansa yellow",
    u'金': "golden",
    u'汉蓝': "han blue",
    u'荧光绿': "fluorescent green",
    u'绿': "green",
    u'砖红': "brick red",
    u'苍紫': "thistle",
    u'刚果粉红': "congo pink",
    u'荧光黄': "fluorescent yellow",
    u'皇竹草绿': "napier green",
    u'淡天蓝': "light sky blue",
    u'深金黄': "dark goldenrod",
    u'深淡蓝': "dark pastel blue",
    u'蒲公英': "dandelion",
    u'木瓜': "papaya whip",
    u'珍珠粉': "pink pearl",
    u'炫蓝': "b'dazzled blue",
    u'博伊森莓': "boysenberry",
    u'暗柔和红': "dark pastel red",
    u'碧玉': "jasper",
    u'深粉': "deep pink",
    u'合金橙': "alloy orange",
    u'蓝铃': "blue bell",
    u'电靛蓝': "electric indigo",
    u'宇宙拿铁': "cosmic latte",
    u'深渊蓝': "abyss",
    u'风滚草': "tumbleweed",
    u'巨人橙': "giants orange",
    u'缎光泽金': "satin sheen gold",
    u'暗淡灰': "dim gray",
    u'中朱砂': "medium vermilion",
    u'粉桃红': "peach puff",
    u'柔和红': "pastel red",
    u'珊瑚粉': "coral pink",
    u'石灰': "heather gray",
    u'枣红': "purplish red",
    u'淡粉红': "light fuchsia pink",
    u'蓝荧光': "fluorescent blue",
    u'海蓝': "sea blue",
    u'透明红': "transparent red",
    u'波斯绿': "persian green",
    u'轻浅蓝': "light cornflower blue",
    u'芹菜绿': "celery green",
    u'浓郁黑': "rich black",
    u'军绿': "army green",
    u'哑光黑': "matte black",
    u'暖白': "warm white",
    u'黑': "black",
    u'驼棕': "camel brown",
    u'法国天蓝': "french sky blue",
    u'柔和橙': "pastel orange",
    u'草绿': "grass green",
    u'黝黑': "dark tan",
    u'深紫红': "prune",
    u'灰黄': "isabelline",
    u'芽绿': "bud green",
    u'波斯红': "persian red",
    u'玫瑰褐': "rosy brown",
    u'钻石': "diamond",
    u'保加利亚玫瑰': "bulgarian rose",
    u'鹿皮': "moccasin",
    u'浅白铜': "pale copper",
    u'香槟': "champagne",
    u'复古玫瑰红': "old rose",
    u'浅珊瑚红': "opera mauve",
    u'薰衣草玫瑰': "lavender rose",
    u'棉花糖': "cotton candy",
    u'玫瑰乌木': "rose ebony",
    u'翠绿': "paris green",
    u'棒棒糖': "lollipop",
    u'暗绿': "sap green",
    u'西班牙铬绿': "spanish viridian",
    u'银沙': "silver sand",
    u'法国覆盆子': "french raspberry",
    u'墨蓝': "ink blue",
    u'沙褐': "sandy brown",
    u'西班牙蓝': "spanish blue",
    u'天蓝': "cerulean blue",
    u'淡金': "pale gold",
    u'深胡萝卜橙': "deep carrot orange",
    u'金属金': "metallic gold",
    u'透明黑': "transparent black",
    u'客串粉红': "cameo pink",
    u'青': "cyan",
    u'深咖': "deep coffee",
    u'橘红': "tangerine",
    u'阿拉斯加蓝': "alaska blue",
    u'玫红': "persian rose",
    u'浅咖': "light coffee",
    u'马鞍棕': "saddle brown",
    u'旧金': "old gold",
    u'迷幻紫': "psychedelic purple",
    u'超粉红': "ultra pink",
    u'秘鲁': "peru",
    u'淡矢车菊蓝': "pale cornflower blue",
    u'土黄': "earth yellow",
    u'锈红': "rusty red",
    u'哥伦比亚蓝': "columbia blue",
    u'战舰灰': "battleship grey",
    u'皇家蔚蓝': "royal azure",
    u'亮橙': "bright orange",
    u'浓郁薰衣草': "rich lavender",
    u'宝石红': "ruby red",
    u'绿灯': "green light",
    u'海洋蓝': "ocean blue",
    u'浅莲红': "fuchsia pink",
    u'中波斯蓝': "medium persian blue",
    u'紫罗兰': "violet",
    u'朱红': "vermilion",
    u'锈': "rust",
    u'紫水晶': "amethyst",
    u'珍珠白': "pearl white",
    u'银白': "silver white",
    u'浅酒红': "light wine red",
    u'桔柚': "tangelo",
    u'小车灰': "trolley grey",
    u'空军蓝': "air force blue",
    u'骨': "bone",
    u'铁锈': "rusty",
    u'蔚蓝霜': "cerulean frost",
    u'粉绿': "pink green",
    u'深红': "ruby",
    u'茶绿': "tea green",
    u'草坪绿': "lawn green",
    u'洋红': "magenta",
    u'光赭红': "light red ochre",
    u'茉莉花': "jasmine",
    u'霓虹绿': "neon green",
    u'沙尘暴': "dust storm",
    u'精彩': "fabulous",
    u'浅豹纹': "light leopard",
    u'犹他赤红': "utah crimson",
    u'柠檬绸': "lemon chiffon",
    u'玫瑰棕': "copper rose",
    u'荧光玫瑰': "fluorescent rose",
    u'樱桃粉红': "cerise pink",
    u'粉墨': "regalia",
    u'中兰花紫': "medium orchid",
    u'古银': "old silver",
    u'紫灰褐': "purple taupe",
}