__author__ = 'Administrator'


JOOM_COLOR = ['Abyss', 'Acid green', 'Aero', 'Aero blue', 'Air Force blue', 'Alabama crimson', 'Alice blue',
              'Alizarin crimson', 'Alloy orange', 'Almond', 'Amaranth', 'Amaranth pink', 'Amazon', 'Amber',
              'Amethyst', 'Android green', 'Anti-flash white', 'Antique brass', 'Antique bronze', 'Antique fuchsia',
              'Antique ruby', 'Antique white', 'Apple green', 'Apricot', 'Aqua', 'Aquamarine', 'Army green', 'Arsenic',
              'Arylide yellow', 'Ash grey', 'Asparagus', 'Atomic tangerine', 'Auburn', 'Aureolin', 'AuroMetalSaurus',
              'Avocado', 'Azure', 'Azure mist', 'B&#39;dazzled blue', 'Baby blue', 'Baby blue eyes', 'Baby pink',
              'Baby powder', 'Baker-Miller pink', 'Ball blue', 'Banana Mania', 'Banana yellow', 'Barbie pink',
              'Barn red', 'Battleship grey', 'Bazaar', 'Beau blue', 'Beaver', 'Beige', 'Big dip o&#39;ruby', 'Bisque',
              'Bistre', 'Bistre brown', 'Bitter lemon', 'Bitter lime', 'Bittersweet', 'Bittersweet shimmer', 'Black',
              'Black bean', 'Black leather jacket', 'Black olive', 'Blanched almond', 'Blast-off bronze',
              'Bleu de France', 'Blizzard Blue', 'Blond', 'Blue', 'Blue Bell', 'Blue-gray', 'Blue-green', 'Blue-violet',
              'Blueberry', 'Bluebonnet', 'Blush', 'Bole', 'Bondi blue', 'Bone', 'Bottle green', 'Boysenberry',
              'Brandeis blue', 'Brass', 'Brick red', 'Bright cerulean', 'Bright green', 'Bright lavender',
              'Bright maroon', 'Bright navy blue', 'Bright pink', 'Bright turquoise', 'Bright ube',
              'Brilliant lavender', 'Brilliant rose', 'Brink pink', 'British racing green', 'Bronze', 'Bronze Yellow',
              'Brown', 'Brown Sugar', 'Brown-nose', 'Brunswick green', 'Bubble gum', 'Bubbles', 'Bud green', 'Buff',
              'Bulgarian rose', 'Burgundy', 'Burlywood', 'Burnt orange', 'Burnt sienna', 'Burnt umber', 'Byzantine',
              'Byzantium', 'CG Blue', 'CG Red', 'Cadet', 'Cadet blue', 'Cadet grey', 'Cadmium green', 'Cadmium orange',
              'Cadmium red', 'Cadmium yellow', 'Cal Poly green', 'Cambridge Blue', 'Camel', 'Cameo pink',
              'Camouflage green', 'Canary yellow', 'Candy apple red', 'Candy pink', 'Capri', 'Caput mortuum',
              'Cardinal', 'Caribbean green', 'Carmine', 'Carmine pink', 'Carmine red', 'Carnation pink', 'Carnelian',
              'Carolina blue', 'Carrot orange', 'Castleton green', 'Catalina blue', 'Catawba', 'Cedar Chest', 'Ceil',
              'Celadon', 'Celadon blue', 'Celadon green', 'Celeste', 'Celestial blue', 'Cerise', 'Cerise pink',
              'Cerulean', 'Cerulean blue', 'Cerulean frost', 'Chamoisee', 'Champagne', 'Charcoal', 'Charleston green',
              'Charm pink', 'Chartreuse', 'Cherry', 'Cherry blossom pink', 'Chestnut', 'China pink', 'China rose',
              'Chinese red', 'Chinese violet', 'Chocolate', 'Chocolate brown', 'Chrome yellow', 'Cinereous', 'Cinnabar',
              'Cinnamon', 'Citrine', 'Citron', 'Claret', 'Classic rose', 'Cocoa brown', 'Coconut', 'Coffee',
              'Columbia blue', 'Congo pink', 'Cool black', 'Cool grey', 'Copper', 'Copper penny', 'Copper red',
              'Copper rose', 'Coquelicot', 'Coral', 'Coral pink', 'Coral red', 'Cordovan', 'Corn', 'Cornell Red',
              'Cornflower blue', 'Cornsilk', 'Cosmic latte', 'Cotton candy', 'Cream', 'Crimson', 'Crimson glory',
              'Cyan', 'Cyber grape', 'Cyber yellow', 'Daffodil', 'Dandelion', 'Dark blue', 'Dark blue-gray',
              'Dark brown', 'Dark byzantium', 'Dark candy apple red', 'Dark cerulean', 'Dark chestnut', 'Dark coral',
              'Dark cyan', 'Dark electric blue', 'Dark goldenrod', 'Dark gray', 'Dark green', 'Dark grey',
              'Dark imperial blue', 'Dark jungle green', 'Dark khaki', 'Dark lava', 'Dark lavender', 'Dark liver',
              'Dark magenta', 'Dark midnight blue', 'Dark moss green', 'Dark olive green', 'Dark orange', 'Dark orchid',
              'Dark pastel blue', 'Dark pastel green', 'Dark pastel purple', 'Dark pastel red', 'Dark pink',
              'Dark powder blue', 'Dark purple', 'Dark raspberry', 'Dark red', 'Dark salmon', 'Dark scarlet',
              'Dark sea green', 'Dark sienna', 'Dark sky blue', 'Dark slate blue', 'Dark slate gray',
              'Dark spring green', 'Dark tan', 'Dark tangerine', 'Dark taupe', 'Dark terra cotta', 'Dark turquoise',
              'Dark vanilla', 'Dark violet', 'Dark yellow', 'Dartmouth green', 'Davy&#39;s grey', 'Debian red',
              'Deep Space Sparkle', 'Deep Taupe', 'Deep Tuscan red', 'Deep carmine', 'Deep carmine pink',
              'Deep carrot orange', 'Deep cerise', 'Deep champagne', 'Deep chestnut', 'Deep coffee', 'Deep fuchsia',
              'Deep jungle green', 'Deep lemon', 'Deep lilac', 'Deep magenta', 'Deep mauve', 'Deep moss green',
              'Deep peach', 'Deep pink', 'Deep ruby', 'Deep saffron', 'Deep sky blue', 'Deer', 'Denim', 'Denim blue',
              'Desert', 'Desert sand', 'Desire', 'Diamond', 'Dim gray', 'Dirt', 'Dodger blue', 'Dogwood rose',
              'Dollar bill', 'Donkey Brown', 'Drab', 'Duke blue', 'Dust storm', 'Dutch white', 'Earth yellow',
              'Ebony', 'Ecru', 'Eggplant', 'Eggshell', 'Egyptian blue', 'Electric blue', 'Electric crimson',
              'Electric cyan', 'Electric green', 'Electric indigo', 'Electric lavender', 'Electric lime',
              'Electric purple', 'Electric ultramarine', 'Electric violet', 'Electric yellow', 'Emerald',
              'Eminence', 'English green', 'English lavender', 'English red', 'English violet', 'Eton blue',
              'Eucalyptus', 'Fallow', 'Falu red', 'Fandango', 'Fandango pink', 'Fashion fuchsia', 'Fawn', 'Feldgrau',
              'Feldspar', 'Fern green', 'Ferrari Red', 'Field drab', 'Fire engine red', 'Firebrick', 'Flame',
              'Flamingo pink', 'Flattery', 'Flavescent', 'Flax', 'Flirt', 'Floral white', 'Fluorescent orange',
              'Fluorescent pink', 'Fluorescent yellow', 'Folly', 'Forest camouflage', 'Forest green', 'French beige',
              'French bistre', 'French blue', 'French lilac', 'French lime', 'French mauve', 'French puce',
              'French raspberry', 'French rose', 'French sky blue', 'French wine', 'Fresh Air', 'Fuchsia',
              'Fuchsia pink', 'Fuchsia rose', 'Fulvous', 'Fushcia', 'Fuzzy Wuzzy', 'Gainsboro', 'Gamboge',
              'Generic viridian', 'Ghost white', 'Giants orange', 'Ginger', 'Glaucous', 'Glitter', 'Gold',
              'Golden brown', 'Golden poppy', 'Golden yellow', 'Goldenrod', 'Granny Smith Apple', 'Grape', 'Gray',
              'Gray-asparagus', 'Gray-blue', 'Green', 'Green-yellow', 'Grey', 'Grullo', 'Guppie green', 'Han blue',
              'Han purple', 'Hansa yellow', 'Harlequin', 'Harvard crimson', 'Harvest gold', 'Heart Gold', 'Heliotrope',
              'Hollywood cerise', 'Honeydew', 'Honolulu blue', 'Hot magenta', 'Hot pink', 'Hunter green', 'Iceberg',
              'Icterine', 'Illuminating Emerald', 'Imperial', 'Imperial blue', 'Imperial purple', 'Imperial red',
              'Inchworm', 'Independence', 'India green', 'Indian red', 'Indian yellow', 'Indigo', 'Indigo dye', 'Iris',
              'Irresistible', 'Isabelline', 'Islamic green', 'Italian sky blue', 'Ivory', 'Jade', 'Japanese indigo',
              'Japanese violet', 'Jasmine', 'Jasper', 'Jazzberry jam', 'Jelly Bean', 'Jet', 'Jonquil', 'June bud',
              'Jungle green', 'KU Crimson', 'Kelly green', 'Kenyan copper', 'Keppel', 'Khaki', 'Kobe', 'Kobi',
              'Kombu green', 'La Salle Green', 'Languid lavender', 'Lapis lazuli', 'Laser Lemon', 'Laurel green',
              'Lava', 'Lavender', 'Lavender blue', 'Lavender blush', 'Lavender gray', 'Lavender indigo',
              'Lavender magenta', 'Lavender mist', 'Lavender pink', 'Lavender purple', 'Lavender rose', 'Lawn green',
              'Lemon', 'Lemon chiffon', 'Lemon curry', 'Lemon glacier', 'Lemon lime', 'Lemon meringue', 'Lemon yellow',
              'Liberty', 'Licorice', 'Light Thulian pink', 'Light apricot', 'Light blue', 'Light brown',
              'Light carmine pink', 'Light coral', 'Light cornflower blue', 'Light crimson', 'Light cyan',
              'Light fuchsia pink', 'Light goldenrod yellow', 'Light gray', 'Light green', 'Light grey', 'Light khaki',
              'Light medium orchid', 'Light moss green', 'Light orchid', 'Light pastel purple', 'Light pink',
              'Light red ochre', 'Light salmon', 'Light salmon pink', 'Light sea green', 'Light sky blue',
              'Light slate gray', 'Light steel blue', 'Light taupe', 'Light yellow', 'Lilac', 'Lime', 'Lime green',
              'Limerick', 'Lincoln green', 'Linen', 'Lion', 'Little boy blue', 'Liver', 'Liver chestnut', 'Livid',
              'Lumber', 'Lust', 'MSU Green', 'Magenta', 'Magenta haze', 'Magic mint', 'Magnolia', 'Mahogany', 'Maize',
              'Majorelle Blue', 'Malachite', 'Manatee', 'Mango Tango', 'Mantis', 'Mardi Gras', 'Maroon', 'Mauve',
              'Mauve taupe', 'Mauvelous', 'May green', 'Maya blue', 'Meat brown', 'Medium Persian blue',
              'Medium Tuscan red', 'Medium aquamarine', 'Medium blue', 'Medium candy apple red', 'Medium carmine',
              'Medium champagne', 'Medium electric blue', 'Medium jungle green', 'Medium lavender magenta',
              'Medium orchid', 'Medium purple', 'Medium red-violet', 'Medium ruby', 'Medium sea green',
              'Medium sky blue', 'Medium slate blue', 'Medium spring bud', 'Medium spring green', 'Medium taupe',
              'Medium turquoise', 'Medium vermilion', 'Medium violet-red', 'Mellow apricot', 'Mellow yellow', 'Melon',
              'Metallic Seaweed', 'Metallic Sunburst', 'Mexican pink', 'Midnight', 'Midnight blue', 'Midnight green',
              'Mikado yellow', 'Mint', 'Mint cream', 'Mint green', 'Misty rose', 'Moccasin', 'Mode beige',
              'Moonstone blue', 'Mordant red 19', 'Moss green', 'Mountain Meadow', 'Mountbatten pink', 'Mughal green',
              'Mulberry', 'Mustard', 'Myrtle green', 'Nadeshiko pink', 'Napier green', 'Naples yellow', 'Navajo white',
              'Navy', 'Navy purple', 'Neon Carrot', 'Neon fuchsia', 'Neon green', 'New Car', 'New York pink',
              'Non-photo blue', 'North Texas Green', 'Nyanza', 'OU Crimson Red', 'Ocean blue', 'Ochre', 'Office green',
              'Old burgundy', 'Old gold', 'Old lace', 'Old lavender', 'Old mauve', 'Old moss green', 'Old rose',
              'Old silver', 'Olive', 'Olive Drab', 'Olivine', 'Onyx', 'Opera mauve', 'Orange', 'Orange peel',
              'Orange-red', 'Orchid', 'Orchid pink', 'Orioles orange', 'Otter brown', 'Outer Space',
              'Outrageous Orange', 'Oxford Blue', 'Pakistan green', 'Palatinate blue', 'Palatinate purple',
              'Pale aqua', 'Pale blue', 'Pale brown', 'Pale carmine', 'Pale cerulean', 'Pale chestnut', 'Pale copper',
              'Pale cornflower blue', 'Pale gold', 'Pale goldenrod', 'Pale green', 'Pale lavender', 'Pale magenta',
              'Pale pink', 'Pale plum', 'Pale red-violet', 'Pale robin egg blue', 'Pale silver', 'Pale spring bud',
              'Pale taupe', 'Pale turquoise', 'Pale violet-red', 'Pansy purple', 'Paolo Veronese green', 'Papaya whip',
              'Paris Green', 'Pastel blue', 'Pastel brown', 'Pastel gray', 'Pastel green', 'Pastel magenta',
              'Pastel orange', 'Pastel pink', 'Pastel purple', 'Pastel red', 'Pastel violet', 'Pastel yellow',
              'Patriarch', 'Payne&#39;s grey', 'Peach', 'Peach puff', 'Peach-orange', 'Peach-yellow', 'Pear', 'Pearl',
              'Pearl Aqua', 'Pearly purple', 'Peridot', 'Periwinkle', 'Persian blue', 'Persian green', 'Persian indigo',
              'Persian orange', 'Persian pink', 'Persian plum', 'Persian red', 'Persian rose', 'Persimmon',
              'Peru', 'Phlox', 'Phthalo blue', 'Phthalo green', 'Pictorial carmine', 'Piggy pink', 'Pine green', 'Pink',
              'Pink Sherbet', 'Pink lace', 'Pink lavender', 'Pink pearl', 'Pink-orange', 'Pistachio', 'Platinum',
              'Plum', 'Popstar', 'Portland Orange', 'Powder blue', 'Princeton orange', 'Prune', 'Prussian blue',
              'Psychedelic purple', 'Puce', 'Puce red', 'Pumpkin', 'Purple', 'Purple Heart', 'Purple mountain majesty',
              'Purple navy', 'Purple pizzazz', 'Purple taupe', 'Purpureus', 'Quartz', 'Queen blue', 'Queen pink',
              'Rackley', 'Radical Red', 'Rajah', 'Raspberry', 'Raspberry glace', 'Raspberry pink', 'Raspberry rose',
              'Raw umber', 'Razzle dazzle rose', 'Razzmatazz', 'Razzmic Berry', 'Red', 'Red-brown', 'Red-orange',
              'Red-violet', 'Redwood', 'Regalia', 'Resolution blue', 'Rhythm', 'Rich black', 'Rich brilliant lavender',
              'Rich carmine', 'Rich electric blue', 'Rich lavender', 'Rich lilac', 'Rich maroon', 'Rifle green',
              'Robin egg blue', 'Rocket metallic', 'Roman silver', 'Rose', 'Rose bonbon', 'Rose ebony', 'Rose gold',
              'Rose madder', 'Rose pink', 'Rose quartz', 'Rose red', 'Rose taupe', 'Rose vale', 'Rosewood',
              'Rosso corsa', 'Rosy brown', 'Royal azure', 'Royal blue', 'Royal fuchsia', 'Royal purple', 'Royal yellow',
              'Ruber', 'Rubine red', 'Ruby', 'Ruby red', 'Ruddy', 'Ruddy brown', 'Ruddy pink', 'Rufous', 'Russet',
              'Russian green', 'Russian violet', 'Rust', 'Rusty red', 'Sacramento State green', 'Saddle brown',
              'Safety orange', 'Safety yellow', 'Saffron', 'Salmon', 'Salmon pink', 'Sand', 'Sand dune', 'Sandstorm',
              'Sandy brown', 'Sandy taupe', 'Sangria', 'Sap green', 'Sapphire', 'Sapphire blue', 'Satin sheen gold',
              'Scarlet', 'Schauss pink', 'School bus yellow', 'Screamin&#39; Green', 'Sea blue', 'Sea green',
              'Seal brown', 'Seashell', 'Selective yellow', 'Sepia', 'Shadow', 'Shampoo', 'Shamrock green',
              'Sheen Green', 'Shimmering Blush', 'Shocking pink', 'Sienna', 'Silver', 'Silver Lake blue',
              'Silver chalice', 'Silver pink', 'Silver sand', 'Sinopia', 'Skobeloff', 'Sky blue', 'Sky magenta',
              'Slate blue', 'Slate gray', 'Smalt', 'Smitten', 'Smoke', 'Smokey topaz', 'Smoky black', 'Snow', 'Soap',
              'Sonic silver', 'Spanish bistre', 'Spanish blue', 'Spanish carmine', 'Spanish crimson', 'Spanish gray',
              'Spanish orange', 'Spanish sky blue', 'Spanish viridian', 'Spartan Crimson', 'Spiro Disco Ball',
              'Spring bud', 'Spring green', 'St. Patrick&#39;s blue', 'Star command blue', 'Steel blue', 'Steel pink',
              'Strawberry', 'Sunglow', 'Sunray', 'Sunset', 'Sunset orange', 'Super pink', 'Tan', 'Tangelo', 'Tangerine',
              'Tangerine yellow', 'Tango pink', 'Taupe', 'Taupe gray', 'Tea green', 'Tea rose', 'Teal', 'Teal blue',
              'Teal deer', 'Teal green', 'Telemagenta', 'Terra cotta', 'Thistle', 'Thulian pink', 'Tickle Me Pink',
              'Tiffany Blue', 'Tiger&#39;s eye', 'Timberwolf', 'Titanium yellow', 'Tomato', 'Toolbox', 'Topaz',
              'Tractor red', 'Transparent Black', 'Transparent White', 'Transparent dark green', 'Transparent pink',
              'Transparent red', 'Trolley Grey', 'Tropical rain forest', 'True Blue', 'Tufts Blue', 'Tulip',
              'Tumbleweed', 'Turkish rose', 'Turquoise', 'Turquoise blue', 'Turquoise green', 'Tuscan', 'Tuscan brown',
              'Tuscan red', 'Tuscan tan', 'Tuscany', 'Twilight lavender', 'Tyrian purple', 'UA blue', 'UA red',
              'UCLA Blue', 'UCLA Gold', 'UFO Green', 'UP Forest green', 'UP Maroon', 'USAFA blue', 'USC Cardinal',
              'USC Gold', 'Ube', 'Ultra pink', 'Ultramarine', 'Ultramarine blue', 'Umber', 'Unbleached silk',
              'United Nations blue', 'Unmellow yellow', 'Urobilin', 'Utah Crimson', 'Vanilla', 'Vanilla ice',
              'Vegas gold', 'Venetian red', 'Verdigris', 'Vermilion', 'Veronica', 'Violet', 'Violet-blue',
              'Violet-red', 'Viridian', 'Viridian green', 'Vivid auburn', 'Vivid burgundy', 'Vivid cerise',
              'Vivid orchid', 'Vivid sky blue', 'Vivid tangerine', 'Vivid violet', 'Warm black', 'Waterspout',
              'Wenge', 'Wheat', 'White', 'White smoke', 'Wild Strawberry', 'Wild Watermelon', 'Wild blue yonder',
              'Wild orchid', 'Windsor tan', 'Wine', 'Wine dregs', 'Wisteria', 'Wood brown', 'Xanadu', 'Yale Blue',
              'Yankees blue', 'Yellow', 'Yellow Orange', 'Yellow rose', 'Yellow-green', 'Zaffre', 'Zinnwaldite brown',
              'Zomp', 'Acid blue', 'African purple', 'Alaska blue', 'Amarillo', 'Amber gold', 'Ambrosial Crush',
              'American rose', 'Antique Black', 'Antique Gold', 'Antique silver', 'Aqua blue', 'Arctic blue',
              'Ash black', 'Asphalt', 'Baby Doll', 'Berry', 'Birch', 'Black brown', 'Black fuchsia', 'Black gray',
              'Black white', 'Black-purple', 'Blue Chocolate', 'Blue Light Wash', 'Blue Wash', 'Blue sapphire',
              'Blue yonder', 'Blue-Cream', 'Bright Orange', 'Bright blue', 'Bright red', 'Brown-Cream',
              'Bubblegum Pink', 'Burgundy Metallic', 'Burgundy Pearl', 'Cafe', 'Calm', 'Camel brown', 'Camouflage',
              'Carbon Fiber Black', 'Celery green', 'Champagne-Orange', 'Checkered Red', 'Checkered White',
              'Cheddar Yellow', 'Cheers', 'Cheetah', 'Cheetah print', 'Cherry Pink', 'Clear', 'Clear Beige',
              'Clear Blue', 'Clear Gray', 'Clear Green', 'Clear Green Pearl', 'Clear Pink', 'Clear Pink Pearl',
              'Cobalt', 'Cocoa', 'Cocoa Bean', 'Coffee Bean Silver Pink', 'Cool white', 'Coral green', 'Crystal Ball',
              'Crystal Clear', 'Dahlia', 'Dark Blue Pearl', 'Dark army green', 'Dark blond', 'Dark blue-silver grey',
              'Dark blue-sky blue', 'Dark brown-army green', 'Dark brown-black', 'Dark coffee', 'Dark plum',
              'Dark red-army green', 'Dark red-black', 'Deep', 'Dinar', 'Dreamscape', 'Earth', 'Emotion', 'Fabulous',
              'Flame red-light khaki', 'Flat Dark Earth', 'Floral', 'Floral print', 'Fluorescence green',
              'Fluorescent blue', 'Fluorescent green', 'Fluorescent rose', 'Flush', 'Frost White', 'Fuchsia-Black',
              'Garnet', 'Giraffe', 'Glistening Sun', 'Gold Fusion', 'Golden', 'Goldfish', 'Goldmine', 'Gradient black',
              'Grass green', 'Green Apple', 'Green Pearl', 'Green light', 'Green plaid', 'Grey White', 'Greyish white',
              'Heather Gray', 'Heather grey', 'Highlight', 'Honey', 'Ink blue', 'Iridescent', 'Irish green',
              'Khaki Beige', 'Khaki Green', 'Lake blue', 'Lake green', 'Latte', 'Leaf', 'Leopard', 'Leopard print',
              'Light Blue Pearl', 'Light beige', 'Light blond', 'Light coffee', 'Light leopard', 'Light purple',
              'Light rose', 'Light tan', 'Light wine red', 'Lollipop', 'Maple', 'Marble', 'Matte Black', 'Matte White',
              'Medium blond', 'Medium brown', 'Metallic Bronze', 'Metallic Gold', 'Metallic Onyx', 'Metallic Pink',
              'Metallic Purple', 'Metallic Red', 'Metallic Silver', 'Mica', 'Midori', 'Milk Chocolate', 'Milk white',
              'Mini Black/White Zebra', 'Mother of Pearl', 'Multicolor', 'Multicolored', 'Nacarat', 'Native Earth',
              'Natural', 'Navy blue', 'Navy blue-lake blue', 'Neon blue', 'Neon orange', 'Neon pink', 'Neon red',
              'Neon yellow', 'Newspaper', 'Noche', 'Nude', 'Yellow light', 'Zebra', 'Zebra print', 'Yellow camouflage',
              'Nutmeg', 'Ocean Boat Blue', 'Off white', 'Off-white', 'Olive green', 'Olive green black', 'Orange light',
              'Orange plaid', 'Orion', 'Peacock blue', 'Stil de grain yellow', 'Stizza', 'Stormcloud', 'Straw',
              'Peak green', 'Pearl White', 'Pink Beige', 'Pink Cheetah', 'Pink Green', 'Pink Purple Green',
              'Pink indigo', 'Pink light', 'Pinky', 'Pure', 'Pure white', 'Purple fuchsia', 'Purple light',
              'Purple-Cream', 'Purple-pink', 'Purplish red', 'Red Hot', 'Red Pearl', 'Red black', 'Red devil',
              'Rose Petal', 'Rose red-light khaki', 'Rust brown', 'Rusty', 'Sandy', 'Sea', 'Sensual', 'Serenity',
              'Sigal', 'Silver gray', 'Silver green', 'Silver grey', 'Silver white', 'Sky', 'Skyblue Orange', 'Slate',
              'Snow White', 'Space cadet', 'Sparkling White', 'Star', 'Steel Blue-Purple', 'Stem', 'Stik-It',
              'Sunset Kiss', 'Sunset Plum', 'Sweet Gold', 'Tiger', 'Tiger print', 'Tortoise', 'Transparent',
              'Turquoise black', 'Turquoise-Purple', 'UV purple', 'Ultra', 'Upsdell red', 'Velvet Touch Pink',
              'Velvet Touch Purple', 'Velvet Touch Zebra', 'Vercafe', 'Verde', 'Viola', 'Warm Yellow', 'Warm white',
              'Washed black', 'Water blue', 'Water wave camouflage', 'Watermelon red', 'White Dye Dip', 'White Glitter',
              'White gold', 'Wine red', 'Wow', 'Yellow Pearl']
